// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

let directUrl: string | undefined = process.env.DIRECT_URL;
let dbUrl = process.env.DATABASE_URL;

if (!directUrl) {
  throw new Error(
    "DIRECT_URL environment variable is not set. Please set it to your database connection string.",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts", 
  },
  datasource: {
    url: directUrl,
  },
});
